name: coffee_app_vgv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  ## State Management  
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  ## Network
  http: ^1.5.0

  ## Utils  
  dartz: ^0.10.1
  share_plus: ^12.0.1
  pinch_zoom: ^2.0.1

  #Testing
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  bloc_test: ^10.0.0

  ## Local Storage
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
